[build]
  base = "frontend"
  command = "npm rebuild esbuild && npm run build"
  publish = "dist"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
