# Generated by Django 4.2 on 2025-06-17 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee_api", "0002_patientprofile_doctorprofile_appointment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["appointment_date", "time_slot"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("09:30-10:30", "9:30 AM to 10:30 AM"),
                    ("11:00-12:30", "11:00 AM to 12:30 PM"),
                    ("14:00-15:30", "2:00 PM to 3:30 PM"),
                    ("16:00-18:00", "4:00 PM to 6:00 PM"),
                ],
                default="09:30-10:30",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("patient", "doctor", "appointment_date", "time_slot")},
        ),
    ]
