# Generated by Django 4.2 on 2025-06-26 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("employee_api", "0003_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-appointment_date", "-time_slot"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="initial_report",
            field=models.FileField(blank=True, null=True, upload_to="patient_reports/"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="suggestion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="suggestion_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("09:30-10:30", "9:30 AM to 10:30 AM"),
                    ("11:00-12:30", "11:00 AM to 12:30 PM"),
                    ("14:00-15:30", "2:00 PM to 3:30 PM"),
                    ("16:00-18:00", "4:00 PM to 6:00 PM"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.permission"
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tablets", models.JSONField(blank=True, default=dict)),
                ("syrups", models.JSONField(blank=True, default=dict)),
                ("injections", models.JSONField(blank=True, default=dict)),
                ("ointments", models.JSONField(blank=True, default=dict)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="doctor_reports/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="employee_api.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
