# Generated by Django 4.2 on 2025-07-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee_api",
            "0004_alter_appointment_options_appointment_initial_report_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="injections",
            new_name="medication_details",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="ointments",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="report_file",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="syrups",
        ),
        migrations.RemoveField(
            model_name="medicalrecord",
            name="tablets",
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="prescribed_tests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="MedicationBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_sent_to_patient", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_bill",
                        to="employee_api.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosticTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("average", "Average"),
                            ("bad", "Bad"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_sent_to_patient", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_tests",
                        to="employee_api.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests_prescribed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests_to_take",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
