# Generated by Django 4.2 on 2025-07-15 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_api', '0005_rename_injections_medicalrecord_medication_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DoctorUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
